language: node_js
sudo: false
node_js:
  - 8
install:
  - npm install
script:
  - npm run bootstrap
  - npm run lint
  - cd packages/aws-amplify && npm run test
  - cd packages/aws-amplify-react && npm run test
  - npm run coverage
  - npm run build
  - npm run docs