language: node_js
sudo: false
node_js:
  - 8
install:
  - yarn
script:
  - yarn bootstrap
  - yarn link
  - yarn test --scope aws-amplify
  - yarn test --scope aws-amplify-react
  - yarn coverage
  - yarn build