language: node_js
sudo: false
node_js:
  - 6
install:
  - yarn
script:
  - yarn bootstrap --concurrency=1
  - yarn test --scope aws-amplify
  - yarn test --scope aws-amplify-react
  - yarn coverage
  - yarn build