language: node_js
sudo: false
node_js:
  - 6
install:
  - yarn
  - yarn config set workspaces-experimental true
script:
  - yarn bootstrap
  - yarn test --scope aws-amplify
  - yarn test --scope aws-amplify-react
  - yarn coverage
  - yarn build