auth:
  auth-memory:
    users:
      foo:
        name: test
        password: test
store:
  memory:
    limit: 1000
uplinks:
  npmjs:
    url: https://registry.yarnpkg.com
packages:
  # '@aws-amplify/*':
  #   access: $all
  #   publish: $all

  # 'aws-amplify':
  #   access: $all
  #   publish: $all

  # 'aws-amplify-*':
  #   access: $all
  #   publish: $all

  # 'amazon-cognito-*':
  #   access: $all
  #   publish: $all

  '@*/*':
    access: $all
    publish: $all
    proxy: npmjs

  '**':
    access: $all
    publish: $all
    proxy: npmjs

middlewares:
  audit:
    enabled: true
logs:
  - { type: stdout, format: pretty, level: trace }
