name: Verdaccio
description: Publishes to Verdaccio
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: yarn install
      shell: bash

    - name: Build packages
      run: yarn build
      shell: bash

    - name: Publish to Verdaccio
      run: yarn publish:verdaccio
      shell: bash
