name: Bundle Size

on:
  pull_request:
    types: [submitted]
    branches: [main]

jobs:
  size:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - uses: andresz1/size-limit-action@v1
      with:
        build_script: test:size
        #github_token: ${{ secrets.GITHUB_TOKEN }}
