name: Bundle Size

on: [pull_request]

jobs:
  bundle-size:
    name: dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn workspace build

      - name: Run bundlewatch
        run: yarn run bundlewatch
        env:
          CI_BRANCH_BASE: main
