name: Bundle Size

on: [pull_request]

jobs:
  bundle-size:
    name: Calculate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: [webpack4, webpack]
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: ./.github/actions/setup-verdaccio-action
      - uses: actions/setup-node@v2
        with:
          registry-url: 'http://localhost:4873'
      # - uses: ./.github/actions/publish-verdaccio-action
      - uses: ./.github/actions/bundle-size-action
        with:
          stack: ${{ matrix.stack }}
