name: Bundle Size

on: [pull_request]

jobs:
  bundle-size:
    name: Calculate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: [webpack4, webpack]
    steps:
      - name: Checkout Amplify JS
        uses: actions/checkout@v2.1.0

      - name: Setup Node + NPM
        uses: actions/setup-node@v2

      - name: Setup Verdaccio
        uses: ./.github/actions/setup-verdaccio-action

      - name: Use Verdaccio as NPM registry
        uses: actions/setup-node@v2
        with:
          registry-url: 'http://localhost:4873'

      # - uses: ./.github/actions/publish-verdaccio-action
      - name: Calculate bundle sizes
        uses: ./.github/actions/bundle-size-action
        with:
          stack: ${{ matrix.stack }}
