name: Bundle Size

on: [pull_request]

jobs:
  bundle-size:
    name: Tree-shaking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: ./.github/actions/bundle-size-action
