name: Bundle Size

on: [pull_request]

jobs:
  bundle-size:
    name: Calculate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn workspace @aws-amplify/core build

      - name: Run bundlewatch
        run: yarn run bundlewatch packages/*/dist/*.min.js --max-size 400kb
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
