name: Bundle Size

on: [pull_request]

jobs:
  bundle-size:
    name: Calculate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: [webpack4, webpack]
    steps:
      - name: Checkout Amplify JS
        uses: actions/checkout@v2

      - name: Setup Node + NPM
        uses: actions/setup-node@v2

      # https://github.com/actions/cache/blob/master/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --prefer-offline

      - name: Build packages
        run: yarn build

      - name: Setup Verdaccio
        uses: ./.github/actions/setup-verdaccio-action

      - name: Use Verdaccio as NPM registry
        uses: actions/setup-node@v2
        with:
          registry-url: 'http://localhost:4873'

      - name: Publish to Verdaccio
        run: npm run publish:verdaccio
        shell: bash

      - name: Calculate bundle sizes
        uses: ./.github/actions/bundle-size-action
        with:
          stack: ${{ matrix.stack }}
