name: Push - release for feature preid

concurrency:
  # group name unique for push to push-preid-release
  group: push-release-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      # Change this to your branch name where "example-preid" corresponds to the preid you want your changes released on
      - fix/release-workflow

jobs:
  workflow-test:
    name: Test PR generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: amplify-js
          token: ${{ secrets.GH_TOKEN_AMPLIFY_JS_WRITE }}

      - name: Create an empty commit
        working-directory: ./amplify-js
        run: |
          git commit --allow-empty -m "Empty-Commit"
          git push origin fix/release-workflow

      - name: Create a PR to merge temporary release branch into main development branch
        working-directory: ./amplify-js
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_AMPLIFY_JS_WRITE }}
        run: |
          gh pr create -B main -H fix/release-workflow --title 'DO NOT MERGE: Test release workflow' --body 'Test release workflow.'             
