name: Push - release from main to unstable

on:
  push:
    branches:
      - main

env:
  GITHUB_EMAIL: ${{ vars.GH_EMAIL }}
  GITHUB_USER: ${{ vars.GH_USER }}

jobs:
  e2e:
    secrets: inherit
    uses: ./.github/workflows/callable-release-verification.yml
  unstable-release:
    needs:
      - e2e
    secrets: inherit
    uses: ./.github/workflows/callable-npm-publish-preid.yml
    with:
      preid: unstable
