name: Push - release from release to latest

on:
  push:
    branches:
      - release

env:
  GITHUB_EMAIL: ${{ vars.GH_EMAIL }}
  GITHUB_USER: ${{ vars.GH_USER }}

jobs:
  e2e:
    secrets: inherit
    uses: ./.github/workflows/callable-release-verification.yml
  release:
    needs:
      - e2e
    permissions:
      contents: write
    secrets: inherit
    uses: ./.github/workflows/callable-npm-publish-release.yml
